import { NextResponse } from "next/server";
import packageJson from "../../../../package.json";

export async function GET() {
  return NextResponse.json({
    id: "ye-translate",
    name: "Translate",
    version: packageJson.version,
    description: "Privacy-friendly translation with saved translations",
    icon: "Languages",
    permissions: ["timeline:write", "widgets:register"],
  surfaceSchemaVersion: 1,
    surfaces: [
    {
      id: "app-settings",
      kind: "settings-panel",
      placement: "app-settings",
      name: "App Settings",
      description: "App-owned settings panel",
      embedPath: "/embed/settings",
      permissions: [],
    },
      {
        id: "quick-translate",
        kind: "widget",
        placement: "dashboard",
        name: "Quick Translate",
        description: "Translate text directly from your dashboard",
        embedPath: "/embed/widget/quick-translate",
        permissions: [],
        defaultSize: { width: 28, height: 25 },
        minSize: { width: 22, height: 18 },
        maxSize: { width: 45, height: 40 },
      },
      {
        id: "recent-translations",
        kind: "widget",
        placement: "dashboard",
        name: "Recent Translations",
        description: "Your most recent translations",
        embedPath: "/embed/widget/recent-translations",
        permissions: [],
        defaultSize: { width: 25, height: 25 },
        minSize: { width: 18, height: 18 },
        maxSize: { width: 45, height: 45 },
        refreshInterval: 300,
      },
      {
        id: "saved-phrases",
        kind: "widget",
        placement: "dashboard",
        name: "Saved Phrases",
        description: "Your bookmarked translations",
        embedPath: "/embed/widget/saved-phrases",
        permissions: [],
        defaultSize: { width: 22, height: 22 },
        minSize: { width: 16, height: 16 },
        maxSize: { width: 40, height: 40 },
        refreshInterval: 300,
      },
      {
        id: "phrase-of-the-day",
        kind: "widget",
        placement: "dashboard",
        name: "Phrase of the Day",
        description: "Learn a new phrase every day",
        embedPath: "/embed/widget/phrase-of-the-day",
        permissions: [],
        defaultSize: { width: 20, height: 18 },
        minSize: { width: 16, height: 14 },
        maxSize: { width: 30, height: 28 },
        refreshInterval: 3600,
      },
      {
        id: "my-activity",
        kind: "widget",
        placement: "dashboard",
        name: "My Activity",
        description: "Your translation activity this week",
        embedPath: "/embed/widget/my-activity",
        permissions: [],
        defaultSize: { width: 22, height: 20 },
        minSize: { width: 16, height: 16 },
        maxSize: { width: 35, height: 30 },
        refreshInterval: 600,
      },
      {
        id: "translation-preview",
        kind: "info-card",
        placement: "timeline",
        name: "Translation preview",
        description: "Translation preview card",
        embedPath: "/embed/card/translation-preview",
        permissions: [],
      },
      {
        id: "translate-text",
        kind: "timeline-card",
        placement: "timeline",
        name: "Text translated",
        description: "Text translation performed",
        embedPath: "/embed/timeline/translation",
        permissions: ["timeline:write"],
        triggers: ["translate-text"],
      },
    ],
    internet: {
      proxy: [
        { host: "api.mymemory.translated.net", paths: ["/get*"], methods: ["GET"], scope: "user" },
      ],
    },
    inter_app: {
      provides: [
        { type: "translate", description: "Translate text between languages" },
      ],
    },
    settings: {
      schema: [
        {
          key: "default_target_lang",
          type: "select",
          label: "Default Target Language",
          default: "en",
          options: [
            { label: "English", value: "en" },
            { label: "Espa\u00f1ol", value: "es" },
            { label: "Fran\u00e7ais", value: "fr" },
            { label: "Deutsch", value: "de" },
            { label: "\u0420\u0443\u0441\u0441\u043a\u0438\u0439", value: "ru" },
          ],
        },
      ],
    },
  });
}
